export const EXERCISE_LIBRARY: Record<string, string[]> = {
  Chest: [
    "Bench Press",
    "Incline Bench Press",
    "Incline Dumbbell Press",
    "Dumbbell Bench Press",
    "Machine Chest Press",
    "Cable Fly",
    "Pec Deck",
    "Dips",
    "Push Ups",
  ],
  Back: [
    "Deadlift",
    "Barbell Row",
    "T Bar Row",
    "Seated Cable Row",
    "Lat Pulldown",
    "Pull Ups",
    "Chin Ups",
    "Single Arm Dumbbell Row",
    "Rear Delt Pull",
    "Straight Arm Pulldown",
  ],
  Shoulders: [
    "Overhead Press",
    "Shoulder Press",
    "Seated Dumbbell Press",
    "Lateral Raises",
    "Front Raises",
    "Rear Delt Fly",
    "Face Pulls",
    "Upright Row",
    "Shrugs",
  ],
  Legs: [
    "Squat",
    "Front Squat",
    "Hack Squat",
    "Leg Press",
    "Bulgarian Split Squat",
    "Lunges",
    "Leg Extensions",
    "Leg Curls",
    "Romanian Deadlift",
    "Good Mornings",
  ],
  Glutes: ["Hip Thrust", "Glute Bridge", "Cable Kickback", "Sumo Deadlift"],
  Calves: ["Standing Calf Raises", "Seated Calf Raises", "Calf Raises"],
  Biceps: [
    "Barbell Curl",
    "Dumbbell Curl",
    "Hammer Curl",
    "Cable Bicep Curl",
    "Preacher Curl",
    "Incline Dumbbell Curl",
    "EZ Bar Curl",
  ],
  Triceps: [
    "Tricep Pushdown",
    "Overhead Tricep Extension",
    "Skull Crushers",
    "Close Grip Bench Press",
    "Cable Overhead Extension",
    "Tricep Kickback",
  ],
  Forearms: ["Wrist Curls", "Reverse Wrist Curls", "Reverse Curl", "Farmer Carry"],
  Core: [
    "Cable Crunch",
    "Hanging Leg Raises",
    "Plank",
    "Ab Wheel Rollout",
    "Russian Twists",
    "Decline Sit Ups",
  ],
};

export const MUSCLE_GROUPS = Object.keys(EXERCISE_LIBRARY);
